### ISSUE TITLE
Imenu

### ISSUE THREAD

**Issue by fniessen** [apg/ant-el#5]
Hello!

When trying to call imenu, I get:

  This buffer cannot use `imenu-default-create-index-function'

Any idea why that can come from?

**Comment by apg** [comment]
I am not aware of any ways in which imenu + ant.el could interact badly. I suspect that there is another problem with another package in your setup.

**Comment by fniessen** [comment]
You mean that you see the list of Ant targets in your Imenu toolbar, when you launch it?

**Comment by apg** [comment]
Meaning, I don't use imenu, and so there was never an attempt to support it. 

It is also the case that ant.el defines no menus. I have used it via key-bindings and `M-x ant` only.

I will happily accept PRs that address your imenu use case, however!
